### ISSUE TITLE
Nav Bar-FIX

### ISSUE THREAD

**Issue by misslame** [misslame/A.J.A.K.#19]
- **Fix the navbar 'Login':**
     We need to use a method for login authentication. The word "login" should change to the user's name that is a dropdown that links to their profile page, and a logout. This should also have a way of authenticating if a business owner is logged in versus a customer account. 

### Do not do any HTML  (@thelegomonster is responsible for the HTML update for business owner communicate with him for any questions/concerns regarding HTML) 

**_Question:_ Why is this mid-tier?**
**Answer:** Front-end HTML is already _mostly_ implemented and ready to go. We need a method that authenticates a user. Look at the attached image for a look at what is needed. 
 
![image](https://user-images.githubusercontent.com/17186785/77242361-cae02e00-6bba-11ea-9b4e-f82ebf78f10c.png)

**Comment by U-k-t** [comment]
User Authentication Needs to be Checked on Each Page and retained site-wide.
