### ISSUE TITLE
Sign-Up/Register Page

### ISSUE THREAD

**Issue by misslame** [misslame/A.J.A.K.#21]
- **Clear Wording:**
Change "Address" to Delivery Address while also allowing user to select what kind of address this is: home/work/etc. Give message that all input fields are mandatory EXCEPT apt. number. 

- **Error Checking:** 
An enhancement on the current error checking. 
             1.  **_Taken Email:_** if the email already exists. 
             2.  **_Email Format Validation:_** if the email imputed is in email format.
             3. **_Password Complexity Validation:_** if the password imputed meets complexity restrictions
             4. **_Password Retype Validation:_** if the passwords typed are the same
             5. **_Complete Form Validation:_** if every mandatory field is filled out. 
             6. **_Error Messages:_** user should be told what they are doing wrong in a pleasing, easy to read manner. Red easy to read font or a pop-up message. 

- **Error Enhancement:**
Mistakes made by the user shouldn't erase the entire form. Suggestion: Highlight the boxes where the error occurs in red.

- **Auto Login:**
If a user successfully inputs all signup information, they should be auto logged in and sent to profile page or back to the previous page. (design choice). 

 **_Question:_ Why does this require a mid-tier AND front-end developer to work together?**
**Answer:** Because you will need email validation and sign up to properly work together. Front-end developer has a higher responsibility than the mid-tier.  Mid-tier responsibility is to ensure that the below works:
>  1.  **_Taken Email:_** if the email already exists.

**Comment by misslame** [comment]
There is a bug that has appeared, server error keeps occurring

**Comment by juliethjar** [comment]
Field Validation has been implemented
